services:
  backend:
    build: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gamecenter
      SPRING_DATASOURCE_USERNAME: sysdba
      SPRING_DATASOURCE_PASSWORD: masterkey

  frontend:
    build: ../frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:16.6
    environment:
      POSTGRES_USER: sysdba
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: gamecenter
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data: