services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: gamecenter
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gamecenter-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - gamecenter-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - gamecenter-network

  nginx:
    image: nginx:alpine
    volumes:
      - ../docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - gamecenter-network

volumes:
  postgres_data:

networks:
  gamecenter-network:
    driver: bridge