services:
  backend:
    build: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gamecenter
      SPRING_DATASOURCE_USERNAME: sysdba
      SPRING_DATASOURCE_PASSWORD: masterkey
    networks:
      - gamecenter-network

  frontend:
    build: ../frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - gamecenter-network

  db:
    image: postgres:16.6
    environment:
      POSTGRES_USER: sysdba
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: gamecenter
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gamecenter-network

  nginx:
    image: nginx:alpine
    ports:
      - "8880:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - gamecenter-network

networks:
  gamecenter-network:
    driver: bridge

volumes:
  postgres_data: