services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: gamecenter
      POSTGRES_USER: sysdba
      POSTGRES_PASSWORD: masterkey
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sysdba -d gamecenter"]
      interval: 2s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gamecenter
      SPRING_DATASOURCE_USERNAME: sysdba
      SPRING_DATASOURCE_PASSWORD: masterkey
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge